### PR TITLE
Changed the code flow

### PR DESCRIPTION
**Pull request by krlc**
Making multiple return statements makes the code much easier to read

### CODE REVIEW

**Comment by krlc** [comment]
Well... the fact that the build fails is not my fault. You should add `go get github.com/PuerkitoBio/goquery` to your .travis.yml

**Comment by Hexilee** [comment]
It seems that encrypted environment `GO111MODULE=on` will be removed in pr, now I fix it. But it still fail because of some bugs?

**Comment by Hexilee** [comment]
Thanks to your pr. I prefer functions with only one return. Although I can tolerate other code styles, I cannot accept pr only for changing code style.

**Comment by krlc** [comment]
According to travis, it is ok with the code, except for the `.travis.yml` again. Goveralls wants the `-repotoken` arg, although, as far as I can see, it is included. It may not see it because of the missing `=`?

**Comment by Hexilee** [comment]
Maybe. Although I never fail because of the missing =...

**Pull request closed without merging**
